version: 2
updates:
  # Keep frontend dependencies up to date
  - package-ecosystem: "npm"
    directory: "/frontend"
    # Check the npm registry for updates at 2am UTC
    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: "build(node): "

    labels:
      - "dependencies"
      - "javascript"

    open-pull-requests-limit: 4

  # Keep E2E dependencies up to date
  - package-ecosystem: "npm"
    directory: "/e2e"
    # Check the npm registry for updates at 2am UTC
    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: "build(e2e): "

    labels:
      - "dependencies"
      - "ci"

    open-pull-requests-limit: 4

  - package-ecosystem: "pip"
    directory: "/backend/requirements/"
    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: "build(python): "

    labels:
      - "dependencies"
      - "python"

    open-pull-requests-limit: 4
