version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/frontend"
    # Check the npm registry for updates at 2am UTC
    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: "pip"
    directory: "/backend"

    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: ":arrow_up:"
