version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`

      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t ankile/indokweb-frontend ./frontend
      - docker build -t ankile/indokweb-backend ./backend
