version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/:cached

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    environment:
      - DATAPORTEN_ID=$DATAPORTEN_ID
      - DATAPORTEN_REDIRECT_URI=$DATAPORTEN_REDIRECT_URI
      - DATAPORTEN_SECRET=$DATAPORTEN_SECRET
      - BOOKING_EMAIL=$BOOKING_EMAIL
      - BOOKING_EMAIL_PASSWORD=$BOOKING_EMAIL_PASSWORD
      - GOOGLE_DRIVE_API_KEY=$GOOGLE_DRIVE_API_KEY
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - DJANGO_ENVIRONMENT=test
volumes:
  postgres_data:
    driver: local
