version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/:cached

  backend:
    restart: always
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
      - DJANGO_DOT_ENV_FILES=.env,.env.development
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      # We have to exclude entrypoints from being mounted as volumes so that
      # Windows users don't bring in their own entrypoints with the incorrect line endings.
      - /usr/src/app/entrypoints
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    environment:
      - NEXT_PUBLIC_INTERNAL_API_URL=http://backend:8000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    expose:
      - 3000

volumes:
  postgres_data:
    driver: local
