version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/:cached

  backend:
    image: backend:production
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    entrypoint: /usr/src/app/entrypoints/integration.sh
    environment:
      - DATAPORTEN_SECRET=${DATAPORTEN_SECRET}
      - GOOGLE_DRIVE_API_KEY=${GOOGLE_DRIVE_API_KEY}
      - VIPPS_SECRET=${VIPPS_SECRET}
      - VIPPS_SUBSCRIPTION_KEY=${VIPPS_SUBSCRIPTION_KEY}
      - DJANGO_READ_DOT_ENV_FILE=true
      - DJANGO_DOT_ENV_FILES=.env.test
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    expose:
      - 8000

  frontend:
    image: frontend:test
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - APP_ENV=test
        - NODE_ENV=test
    ports:
      - 3000:3000
    expose:
      - 3000

volumes:
  postgres_data:
    driver: local
