name: Python Linting

on:
  push:
  pull_request:
    types: [opened]

jobs:
  flake:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Flake8 Lint
        uses: py-actions/flake8@v1
        with:
          path: "backend/"
          args: "--append-config=backend/tox.ini"

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Repository
        uses: actions/checkout@v2

      - name: Black Lint
        uses: psf/black@stable
        with:
          options: "--check"
          src: "./backend"
