on:
  pull_request:
    paths:
      - "frontend/"

name: Build frontend image

jobs:
  build:
    name: Build frontend image
    id: build-image
    uses: docker/build-push-action@v2
    env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      IMAGE_TAG: ${{ github.sha }}
      NEXT_PUBLIC_GRAPHQL_BACKEND_URI: "https://api.indokntnu.no/graphql"
      NEXT_PUBLIC_FRONTEND_URI: "https://indokntnu.no"
      DATAPORTEN_ID: "f17d2ea0-a7c9-4458-83bf-35cf5b555cae"
      DATAPORTEN_REDIRECT_URI: "https://indokntnu.no/authCallback"
      NEXT_PUBLIC_DATAPORTEN_STATE: "RGpBPYszuqXVvsma1suHJJ4X7ZJjkfS6njRHnx4p"
    with:
      context: ./frontend
      secrets: |
        "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
        "NEXT_PUBLIC_GRAPHQL_BACKEND_URI=${{ env.NEXT_PUBLIC_GRAPHQL_BACKEND_URI }}"
        "NEXT_CONTAINER_GRAPHQL_BACKEND_URI=${{ env.NEXT_CONTAINER_GRAPHQL_BACKEND_URI }}"
        "NEXT_PUBLIC_DATAPORTEN_ID=${{ env.NEXT_PUBLIC_DATAPORTEN_ID}}"
        "NEXT_PUBLIC_DATAPORTEN_REDIRECT_URI=${{ env.NEXT_PUBLIC_DATAPORTEN_REDIRECT_URI}}"
        "NEXT_PUBLIC_DATAPORTEN_STATE=${{ env.NEXT_PUBLIC_DATAPORTEN_STATE}}"
