name: Build images

on: pull_request

env:
  AWS_REGION: eu-north-1 # Set this to our AWS region

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [frontend, backend]
        stage: [staging, production]
        include:
          - image: frontend
            build-env: true
            env-prefix: next
            context: ./frontend
            dockerfile: Dockerfile.prod
          - image: backend
            env-prefix: django
            context: ./backend
            dockerfile: Dockerfile.prod
        exclude:
          - image: backend
            stage: staging
      fail-fast: false

    env:
      env-file: ${{ matrix.env-prefix }}.${{ matrix.stage }}.env
      dockerfile: ${{ matrix.image }}-${{ matrix.stage }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Load environment variables from S3
        if: ${{ matrix.build-env }}
        id: env-download
        run: |
          aws s3 cp s3://indok-web-environments/${{ env.env-file }} ${{ env.env-file }}
          cat ${{ env.env-file }} >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.image }} image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          outputs: type=docker,dest=/tmp/${{ env.dockerfile }}.tar
          tags: ${{ matrix.image }}:${{ matrix.stage }}
          secret-files: |
            ENVIRONMENT=./${{ env.env-file }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.dockerfile }}
          path: /tmp/${{ env.dockerfile }}.tar
          if-no-files-found: error
          retention-days: 1

  api:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-production
          path: /tmp

      - name: Run API tests
        run: docker run -v $(PWD):/usr/src/app backend:production
