name: Integration Testing

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  DATAPORTEN_ID: ${{ secrets.DATAPORTEN_ID }}
  DATAPORTEN_REDIRECT_URI: ${{ secrets.DATAPORTEN_REDIRECT_URI }}
  DATAPORTEN_SECRET: ${{ secrets.DATAPORTEN_SECRET }}
  GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  NEXT_PUBLIC_GRAPHQL_BACKEND_URI: http://localhost:8000/graphql
  NEXT_PUBLIC_DATAPORTEN_ID: fcaa9e30-a6d3-4809-8fea-cdd7b3de1c98
  NEXT_PUBLIC_DATAPORTEN_REDIRECT_URI: http://localhost:3000/authCallback
  NEXT_PUBLIC_DATAPORTEN_STATE: erhgouvwhwiuethviu3htvuq34hvt9uh
  NEXT_PUBLIC_FRONTEND_URI: http://localhost:3000
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  test:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the project
        run: docker-compose -f docker-compose.integration.yml up -d

      - name: Run Cypress Tests
        run: |
          docker-compose exec -T frontend npx cypress run
