name: Django Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  DATAPORTEN_ID: ${{ secrets.DATAPORTEN_ID }}
  DATAPORTEN_REDIRECT_URI: ${{ secrets.DATAPORTEN_REDIRECT_URI }}
  DATAPORTEN_SECRET: ${{ secrets.DATAPORTEN_SECRET }}
  GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  IMAGE_TAG: backend-dummy-image

jobs:
  test:
    name: API tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the project
        run: docker build -f backend/Dockerfile -t ${{ env.IMAGE_TAG }} backend/

      - name: Run the Django API tests
        run: |
          chmod +x backend/test.sh
          backend/test.sh ${{ env.IMAGE_TAG }}
        env:
          DB_HOST: postgres
